/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as LogRouteImport } from './routes/log'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as AssistantRouteImport } from './routes/assistant'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/assistant': typeof AssistantRoute
  '/benchmarks': typeof BenchmarksRoute
  '/history': typeof HistoryRoute
  '/hotel': typeof HotelRoute
  '/log': typeof LogRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/assistant': typeof AssistantRoute
  '/benchmarks': typeof BenchmarksRoute
  '/history': typeof HistoryRoute
  '/hotel': typeof HotelRoute
  '/log': typeof LogRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/assistant': typeof AssistantRoute
  '/benchmarks': typeof BenchmarksRoute
  '/history': typeof HistoryRoute
  '/hotel': typeof HotelRoute
  '/log': typeof LogRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/assistant'
    | '/benchmarks'
    | '/history'
    | '/hotel'
    | '/log'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assistant'
    | '/benchmarks'
    | '/history'
    | '/hotel'
    | '/log'
    | '/workspace'
  id:
    | '__root__'
    | '/assistant'
    | '/benchmarks'
    | '/history'
    | '/hotel'
    | '/log'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AssistantRoute: typeof AssistantRoute
  BenchmarksRoute: typeof BenchmarksRoute
  HistoryRoute: typeof HistoryRoute
  HotelRoute: typeof HotelRoute
  LogRoute: typeof LogRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AssistantRoute: AssistantRoute,
  BenchmarksRoute: BenchmarksRoute,
  HistoryRoute: HistoryRoute,
  HotelRoute: HotelRoute,
  LogRoute: LogRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
